### PR TITLE
Remove Z3 version hardcoding

### PR DESCRIPTION
**Pull request by es3n1n**
that’s pretty much it 

https://github.com/HexRaysSA/goomba/blob/main/makefile#L18

### CODE REVIEW

**Comment by 0xeb** [comment]
Seconded.

Or update https://github.com/HexRaysSA/goomba/blob/main/z3/readme.txt which says 4.11.2 (conflicting with the makefile).

**Comment by es3n1n** [comment]
Totally forgot about this file. I think we should stick to the latest version anyways.

**Comment by 0xeb** [comment]
In that case, the Makefile should then not hardcode the version numbers.

Basically, we unzip the contents of 'bin' and 'include' to <goomba>/z3/[include|bin] (without having <goomba>\z3\z3-version\...).

We update the README.txt in the z3 folder to instruct how to unzip and to get latest sources.

**Comment by es3n1n** [comment]
Sounds reasonable. 

It still makes me wonder why was that path hardcoded in the first place. 

But yeah, i think i should just better remove this hardcoded path and correct instructions on how to unzip the z3 release in this folder.

**Comment by 0xeb** [comment]
I thought it was hardcoded because they mentioned the specific versions in the readme.txt leading me to think that they require a specific version (for some reason).

I tried with 4.11.2 and it seems you tried with latest. Both work.

No need to hard code, just update readme.txt extraction instructions, update makefile to remove version hardcoding.

**Comment by es3n1n** [comment]
So yeah, i removed the version hardcoding. 

Yet the `Z3BIN` option still exists so you technically can still switch z3 bins from the makefile if you want it. 

Looks more user-friendly at least for me.

**Pull request merged**
